baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
disableKinds = ["RSS"]
publishDir = "public"

[Author]
  name = "Dustin Brown"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Djordje Atlialp"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

  customSCSS = ["scss/custom.scss"]

# Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:;me@dustinbrown.dev"

  [[params.social]]
    name = "github"
    url  = "https://github.com/dustinbrownman"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/dustinbrownman"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/dustinbrownman"

[languages]
  [languages.en]
    title = "Dustin Brown"
    subtitle = "Software Engineer, Web Developer"
    keywords = "keyword"
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"
    [[languages.en.menu.main]]
        identifier = "contact"
        name       = "Contact"
        url        = "mailto:me@dustinbrown.dev"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"